name: Feature request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - segovoni
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest an idea for this project!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Is your feature request related to a problem? Please describe
      placeholder: Tell us what you see!
      value: "A clear and concise description of what the problem is. Ex. I'm always frustrated when..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Describe the solution you'd like
      placeholder: Tell us what you'd like to have!
      value: "A clear and concise description of what you want to happen"
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe alternatives you've considered
      placeholder: Tell us your alternatives!
      value: "A clear and concise description of any alternative solutions or features you've considered"
    validations:
      required: false
